name: PR Helper

on: pull_request

jobs:
  prhelper_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run PR Helper
      id: runprhelper
      uses: Matticusau/pr-helper@v1.2.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        enable-prmerge-automation: true
        enable-prcomment-automation: true
        enable-prlabel-automation: true
        enable-prreviewer-frontmatter: false
        enable-welcomemessage: true
        welcome-message: "Thanks for opening your first pull request!Happy Coding!!!!"
        prmerge-requireallchecks: true
        prmerge-requirereviewcount: -1
        prmerge-method: 'merge'
        prmerge-pathcheck: true
        prmerge-allowpaths: "{'any':['./**']}"
        prlabel-default: 'pr-onhold'
        prlabel-ready: 'pr-ready'
        prlabel-onhold: 'pr-onhold'
        prlabel-reviewrequired: 'review-required'
        prlabel-automerge: 'auto-merge'
